pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-creds')   // Docker Hub creds
        SSH_KEY = credentials('aws-ssh-key')                     // PEM file for Ansible
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Push Docker Image') {
            agent { label 'docker-slave' }   // run this on the slave where Docker is installed
            steps {
                sh """
                  docker build -t ${DOCKERHUB_CREDENTIALS_USR}/devops-dev-project:${BUILD_NUMBER} .
                  echo ${DOCKERHUB_CREDENTIALS_PSW} | docker login -u ${DOCKERHUB_CREDENTIALS_USR} --password-stdin
                  docker push ${DOCKERHUB_CREDENTIALS_USR}/devops-dev-project:${BUILD_NUMBER}
                """
            }
        }

        stage('Deploy to Dev') {
            agent { label 'master' }   // run this stage on master where Ansible is installed
            steps {
                sh """
                  ansible-playbook -i ansible/inventory.ini ansible/deploy.yml \
                    --extra-vars "env=dev image_tag=${BUILD_NUMBER} dockerhub_repo=${DOCKERHUB_CREDENTIALS_USR}/devops-dev-project"
                """
            }
        }

        stage('Approve for QA?') {
            steps {
                input message: "Promote to QA?", ok: "Deploy"
            }
        }

        stage('Deploy to QA') {
            agent { label 'master' }
            steps {
                sh """
                  ansible-playbook -i ansible/inventory.ini ansible/deploy.yml \
                    --extra-vars "env=qa image_tag=${BUILD_NUMBER} dockerhub_repo=${DOCKERHUB_CREDENTIALS_USR}/devops-dev-project"
                """
            }
        }

       /* stage('Approve for Staging?') {
            steps {
                input message: "Promote to Staging?", ok: "Deploy"
            }
        }

        stage('Deploy to Staging') {
            agent { label 'master' }
            steps {
                sh """
                  ansible-playbook -i ansible/inventory.ini ansible/deploy.yml \
                    --extra-vars "env=staging image_tag=${BUILD_NUMBER} dockerhub_repo=${DOCKERHUB_CREDENTIALS_USR}/devops-dev-project"
                """
            }
        }

        stage('Approve for Production?') {
            steps {
                input message: "Promote to Production?", ok: "Deploy"
            }
        }

        stage('Deploy to Production') {
            agent { label 'master' }
            steps {
                sh """
                  ansible-playbook -i ansible/inventory.ini ansible/deploy.yml \
                    --extra-vars "env=prod image_tag=${BUILD_NUMBER} dockerhub_repo=${DOCKERHUB_CREDENTIALS_USR}/devops-dev-project"
                """
            }
        }*/
    }
}
