---
- name: Deploy containerized app
  hosts: "{{ env }}"
  become: yes
  vars:
    image_tag: "latest"  # overridden by --extra-vars
  tasks:
    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Login to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: "{{ lookup('env', 'DOCKERHUB_USERNAME') }}"
        password: "{{ lookup('env', 'DOCKERHUB_TOKEN') }}"

    - name: Pull image
      community.docker.docker_image:
        name: "{{ dockerhub_repo }}"
        tag: "{{ image_tag }}"
        source: pull

    - name: Run/Update container
      community.docker.docker_container:
        name: "{{ app_name }}-{{ env }}"
        image: "{{ dockerhub_repo }}:{{ image_tag }}"
        recreate: true
        restart_policy: always
        env: "{{ env_vars | default({}) }}"
        ports:
          - "{{ app_port }}:8080"
